sudo: required
services:
    - docker

before_install:
    - docker build -t book5017/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true book5017/react-test npm test

after_sucess:
    - docker build -t book5017/multi-client ./client
    - docker build -t book5017/multi-nginx ./nginx
    - docker build -t book5017/multi-server ./server
    - docker build -t book5017/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    # - docker push jakethecoder/mutl-client
    # - docker push jakethecoder/mutl-nginx
    # - docker push jakethecoder/mutl-server
    # - docker push jakethecoder/mutl-worker

    - docker push book5017/multi-client
    - docker push book5017/multi-nginx
    - docker push book5017/multi-server
    - docker push book5017/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-1-721805387219
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

