sudo: required
services:
    - docker

before_install:
    - docker build -t jake/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jake/react-test npm test

after_sucess:
    - docker build -t jake/multi-client ./client
    - docker build -t jake/multi-nginx ./nginx
    - docker build -t jake/multi-server ./server
    - docker build -t jake/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password_stdin

    # Take those images and push them to docker hub
    # - docker push jakethecoder/mutl-client
    # - docker push jakethecoder/mutl-nginx
    # - docker push jakethecoder/mutl-server
    # - docker push jakethecoder/mutl-worker

    - docker push book5017/mutl-client
    - docker push book5017/mutl-nginx
    - docker push book5017/mutl-server
    - docker push book5017/mutl-worker